### ISSUE TITLE
h5 error

### ISSUE THREAD

**Issue by MichelMoser** [kishwarshafin/helen#10]
Hi, 

I run into following error troubles with when running helen (CPU only installation) on a flye-assembly: 

```
python3 ~/tools/helen/call_consensus.py -i . -m /net/fs-1/home01/michelmo/tools/helen/r941_flip231_v001.pkl
INFO: OUTPUT DIRECTORY: ./output/
INFO: TORCH THREADS SET TO: 1.
Loading data
Traceback (most recent call last):
  File "/mnt/users/michelmo/tools/helen/call_consensus.py", line 133, in <module>
    FLAGS.gpu_mode)
  File "/mnt/users/michelmo/tools/helen/call_consensus.py", line 53, in polish_genome
    predict(image_filepath, output_filename, model_path, batch_size, num_workers, threads, gpu_mode)
  File "/net/fs-1/home01/michelmo/tools/helen/modules/python/models/predict.py", line 61, in predict
    test_data = SequenceDataset(test_file)
  File "/net/fs-1/home01/michelmo/tools/helen/modules/python/models/dataloader_predict.py", line 35, in __init__
    with h5py.File(hdf5_file_path, 'r') as hdf5_file:
  File "/mnt/users/michelmo/.conda/envs/HELEN/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/mnt/users/michelmo/.conda/envs/HELEN/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

I suspect that h5-files are somehow corrupted (some are empty), but thats difficult to assess for me. I thought the size of total images would be larger than the 5.9 M i got from a 2.5 Gb genome. 

```
total 5.9M
420K mGimageRainbowtrout.T00.h5  212K mGimageRainbowtrout.T11.h5  316K mGimageRainbowtrout.T22.h5
212K mGimageRainbowtrout.T01.h5     0 mGimageRainbowtrout.T12.h5     0 mGimageRainbowtrout.T23.h5
212K mGimageRainbowtrout.T02.h5     0 mGimageRainbowtrout.T13.h5  212K mGimageRainbowtrout.T24.h5
   0 mGimageRainbowtrout.T03.h5  212K mGimageRainbowtrout.T14.h5  212K mGimageRainbowtrout.T25.h5
420K mGimageRainbowtrout.T04.h5  212K mGimageRainbowtrout.T15.h5  420K mGimageRainbowtrout.T26.h5
212K mGimageRainbowtrout.T05.h5     0 mGimageRainbowtrout.T16.h5     0 mGimageRainbowtrout.T27.h5
212K mGimageRainbowtrout.T06.h5     0 mGimageRainbowtrout.T17.h5     0 mGimageRainbowtrout.T28.h5
   0 mGimageRainbowtrout.T07.h5  212K mGimageRainbowtrout.T18.h5  212K mGimageRainbowtrout.T29.h5
420K mGimageRainbowtrout.T08.h5  212K mGimageRainbowtrout.T19.h5  212K mGimageRainbowtrout.T30.h5
   0 mGimageRainbowtrout.T09.h5  420K mGimageRainbowtrout.T20.h5  212K mGimageRainbowtrout.T31.h5
420K mGimageRainbowtrout.T10.h5  212K mGimageRainbowtrout.T21.h5

```

MarginPolish was run with default settings: 

```
/marginPolish $BAM \
$ASM \
/net/fs-1/home01/michelmo/tools/marginPolish/params/allParams.np.human.guppy-ff-233.json \
-t 32 \
-o mGimageRainbowtrout \
-f 2>&1 | tee mG.log
```

Any ideas or hints about what could have gone wrong would be appreciated.

Michel

**Comment by kishwarshafin** [comment]
Hello Michel,

the message `(file signature not found)` indicates that the h5 files are corrupted. To figure out what exactly is going wrong, 
1) can you please tell us the BAM file's size and coverage?
2) what's the size of the genome you get from MarginPolish? 
3) what command did you run to generate the BAM file? 
4) Is there any way you can provide the log file of MarginPolish run?

Also, I would recommend setting the `-o` of MarginPolish with an absolute path. If your output directory contains files from multiple runs then HELEN's file reading method won't work. Same goes for the `-i` for HELEN.

**Comment by MichelMoser** [comment]
Hi, 
Thanks for the quick reply. 

1. can you please tell us the BAM file's size and coverage?
2. what's the size of the genome you get from MarginPolish?

Its about 20x genome coverage in the BAM.
```
ls -hs 
2.5G marginpolish_imageRainbowtrout.fa
65G reads_2_assembly.bam   
22M reads_2_assembly.bam.bai
```

3. what command did you run to generate the BAM file?

```
minimap2 -ax map-ont -t 32 $ASM $FASTQ | samtools view -b |samtools sort -@ 32 > reads_2_assembly.bam

```

4. Is there any way you can provide the log file of MarginPolish run?

[mG.log](https://github.com/kishwarshafin/helen/files/3349721/mG.log)


The log actually didnt seem too informative about potential errors. 
But i had another dataset where i tried to run MarginPolish - Helen, which had similar behaviour (dying after marginPolish step) where i got a log ending with: 

```
> T25_C00091 Performing feature generation for chunk.
  T25_C00091 Writing HELEN features with filename base: splitRleWeight.C00091.contig_101-950-2050
> T02_C00082 Chunk with 26 reads and 17K nucleotides processed in 2 sec
*** Error in `/net/fs-1/home01/michelmo/tools/marginPolish/build/marginPolish': double free or corruption (fasttop): 0x00007f6758ceef00 ***
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 0:
  #000: H5G.c line 310 in H5Gcreate2(): unable to create group
    major: Symbol table
    minor: Unable to initialize object
  #001: H5Gint.c line 194 in H5G__create_named(): unable to create and link to group
    major: Symbol table
    minor: Unable to initialize object
  #002: H5L.c line 1638 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1882 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found

```
Full log here:
[mGMudminnow.log](https://github.com/kishwarshafin/helen/files/3349745/mGMudminnow.log)

Thanks, 
Michel

**Comment by kishwarshafin** [comment]
@tpesout , looks like the error is on MarginPolish side of things? `double free or corruption (fasttop)` would suggest a malloc went wrong? The HDF5 library might be the issue. 
Is there any way we can re-generate this error locally? 

@MichelMoser , thank you so much for reporting and using this tool. All the steps look right. Can you also tell us which platform are you using? Is it ubuntu?

**Comment by MichelMoser** [comment]
I also think hdf5 lib might be the issue. What version did you test it for?
I am using a CentOS 7 cluster.

**Comment by kishwarshafin** [comment]
On our machine, this works:
```bash
$ dpkg -l | grep hdf5
ii  hdf5-helpers                               1.10.0-patch1+docs-4                         amd64        Hierarchical Data Format 5 (HDF5) - Helper tools
ii  libhdf5-100:amd64                          1.10.0-patch1+docs-4                         amd64        Hierarchical Data Format 5 (HDF5) - runtime files - serial version
ii  libhdf5-cpp-100:amd64                      1.10.0-patch1+docs-4                         amd64        Hierarchical Data Format 5 (HDF5) - C++ libraries
ii  libhdf5-dev                                1.10.0-patch1+docs-4                         amd64        Hierarchical Data Format 5 (HDF5) - development files - serial version
ii  libhdf5-serial-dev                         1.10.0-patch1+docs-4                         all          transitional dummy package
ii  libjhdf5-java                              2.11.0+dfsg-3                                amd64        Java HDF5 Object Package
ii  libjhdf5-jni                               2.11.0+dfsg-3                                amd64        Java HDF5 Object Package (Java JNI library)
```

Can you please let us know what version you are on?

**Comment by kishwarshafin** [comment]
Actually, I think this would be more useful for you:

```bash
$ dpkg -s libhdf5-dev
Package: libhdf5-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 11294
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: hdf5
Version: 1.10.0-patch1+docs-4
Replaces: libhdf5-serial-dev (<< 1.8.12-9~)
Provides: libhdf5-serial-dev
Depends: libhdf5-100 (= 1.10.0-patch1+docs-4), zlib1g-dev, libjpeg-dev, libaec-dev, hdf5-helpers, libhdf5-cpp-100 (= 1.10.0-patch1+docs-4)
Suggests: libhdf5-doc
Breaks: libhdf5-serial-dev (<< 1.8.12-9~)
Description: Hierarchical Data Format 5 (HDF5) - development files - serial version
 HDF5 is a file format and library for storing scientific data.
 HDF5 was designed and implemented to address the deficiencies of
 HDF4.x. It has a more powerful and flexible data model, supports
 files larger than 2 GB, and supports parallel I/O.
 .
 This package contains development files for serial platforms.
Original-Maintainer: Debian GIS Project <pkg-grass-devel@lists.alioth.debian.org>
Homepage: http://hdfgroup.org/HDF5/
```

**Comment by MichelMoser** [comment]
we are actually using Module package and not dpkg
loaded hdf5/1.8.11 for marginPolish installation

**Comment by kishwarshafin** [comment]
Ok, can you try it with 1.10.0 or later? I don't think we have tested our pipeline with older hdf5 libraries. I am sure 1.10.3 works too.

**Comment by MichelMoser** [comment]
i will try and report back

**Comment by tpesout** [comment]
I noticed this hdf5 error in the mGMudminnow.log file: 

>   #029: H5HL.c line 139 in H5HL_create(): unable to allocate file memory
>     major: Heap
>     minor: Can't allocate space
>   #030: H5MF.c line 449 in H5MF_alloc(): error locating free space in file
>     major: Resource unavailable
>     minor: Can't allocate space

..which makes me wonder if it is a disk space or memory usage issue.  We've found that MP needs around (but less than) 2GB per thread; how much memory does your machine have?

**Comment by MichelMoser** [comment]
The machine has 3 TB of RAM. So this should not be an issue. 

We updated to hdf5 1.10.5 but the error persists.

```
> T07_C00011 Running polishing algorithm with 50 reads and 37K nucleotides
  T03 Took   0 seconds to generate initial POA
  T03 Starting realignment with score: 42612.0073
  T03 Got avg. coverage: 71.944090 for region of length: 748 and avg. candidate weight of: 12.966183
*** Error in `/mnt/SCRATCH/torfn/apps/marginPolish/build/marginPolish': double free or corruption (fasttop): 0x00007f80e910e750 ***
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5G.c line 323 in H5Gcreate2(): unable to create group
    major: Symbol table
    minor: Unable to initialize object
  #001: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5Gint.c line 157 in H5G__create_named(): unable to create and link to group
    major: Symbol table
    minor: Unable to initialize object
  #002: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5L.c line 1557 in H5L_link_object(): <A0><DA>3<E9><80>^?
    major: Links
    minor: Unable to initialize object
  #003: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5L.c line 1798 in H5L__create_real(): can't insert link
    major: Links

```

**Comment by MichelMoser** [comment]
Here the full log: 

[HELEN_MudM_13521451_1.log](https://github.com/kishwarshafin/helen/files/3354708/HELEN_MudM_13521451_1.log)

**Comment by tpesout** [comment]
Thanks Michel!  I'm not sure what exactly the error is, but my guess is that this is related somehow to CentOS vs Ubuntu.  Regardless, I've made a Docker image that *should* be platform-independent.  There is some documentation on the README here: 
https://github.com/UCSC-nanopore-cgl/MarginPolish/tree/docker#docker

..but in short, you should be able to:
```
docker pull tpesout/margin_polish:latest
docker run -v </your/current/directory>:/data tpesout/margin_polish:latest --help
docker run -v </your/current/directory>:/data tpesout/margin_polish:latest input.bam input.assembly params.json -t 16 -f
```

Please try this and let us know if it works for you!

**Comment by MichelMoser** [comment]
Great, thank you so much for the effort. i will test it.

**Comment by MichelMoser** [comment]
works like a charm!
Thanks again

**Comment by kishwarshafin** [comment]
Great! Thank for closing the issue Michel. Let us know if you need any more help.

**Comment by carsweshau** [comment]
Hello Kishwar Shafin,

Thank you very much for your work on MarginPolish-HELEN! Just as an addition to this closed issue, I've been benchmarking nanopolish / medaka+racon on a CentOS 7 HPC and wanted to include Margin-Polish-HELEN in the analysis. The below example code generates the double free or corruption (fasttop) HDF5 error as described above, however if I remove the `-f` parameter it finishes polishing.

I cannot use the above Docker solution as our HPC setup prevents it, including the rootless setup of Docker.

I would like the ability to run helen polish using the produced images, which requires the `-f` parameter - any help would be most appreciated!

```
#!/bin/bash
#$ -S /bin/bash
#$ -terse
#$ -cwd
#$ -N MARPOLRD 
#$ -V
#$ -l mem_requested=16G
#$ -l h_vmem=16G
#$ -pe smp 144

BAM=${1}
FASTA=${2}
PARAMS=/share/ClusterShare/software/contrib/shacar/marginPolish/params/allParams.np.human.r94-g344.json

module load gi/cmake/3.6.1

marginPolish=/share/ClusterShare/software/contrib/shacar/marginPolish/build/marginPolish

${marginPolish} ${BAM} ${FASTA} ${PARAMS} -t 16 -o marginPolish_output/marginPolish.r94-g344 -f
```

**Comment by kishwarshafin** [comment]
hi @carsweshau ,

this has now become a known problem that the compatible HDF5 library does not work on CentOS. Can you please see if you can install and run PEPPER (https://github.com/kishwarshafin/pepper) internally? If yes, please let me know. So far, we have been seeing the same-level of improvements with PEPPER, as with MP-HELEN. I can guide you on how to run it for your sample.

**Comment by carsweshau** [comment]
Thank you for the prompt reply - I'll look into PEPPER today and let you know how it goes, cheers!

**Comment by tbooth** [comment]
Hi I know it's generally bad form to comment on a closed bug but I was having some issues with MarginPolish and Google led me here. Since I believe I solved my problem I just wanted to add a brief note for anyone stuck in the same place and reading this bug report. Specifically, when running marginPolish with the `-t 16` and `-f` flags I got a whole soup of errors from the HDF5 library very much like those reported by @MichelMoser above.

Using `-t 1` worked fine, indicating this is a threading problem, and indeed my HDF5 was compiled non-thread-safe (oops, but this is actually the default setting).

Downloading the latest HDF5 1.12.0 source, building that with the `--enable-threadsafe --disable-hl` flags, and linking MarginPolish to my shiny new threadsafe hdf5 build solved my problems (I did this by linking statically but I'd imagine supplying an alternative libhdf5.so would work too). This was on CentOS 8.

**Comment by kishwarshafin** [comment]
Thank you @tbooth ,

Greatly appreciated. Please use PEPPER if your data is guppy305 or higher (https://github.com/kishwarshafin/pepper/releases/tag/v0.1) I need to update the readme but PEPPER is outperforming MarginPolish-HELEN on most cases.
