### ISSUE TITLE
Plant species

### ISSUE THREAD

**Issue by Jolvii85** [kishwarshafin/helen#15]
Hi kishwar
Can I use this polisher on complex plant genome? 
Does the model trained with human sequencing data work for the plant species?

Thank you.

Jolvii

**Comment by kishwarshafin** [comment]
Hi Jolvii,

The model will treat the genome as a homozygous sequence. We have not benchmarked any plant genome, but if you have sequencing data and a high-quality assembly that we can use as a ground truth then we can do a quick test and let you know. (None of us are plant genome experts :( sorry)

Best,
Kishwar

**Comment by reachsagaya** [comment]
Hi Kishwar,

I have a similar question and I work with plant genome as well.  
While choosing params.json when running Margin polish, can I use allParams.np.human.guppy-ff-235.json for the plant genome or should I use allParams.np.json.
Next if I shared with you my draft plant shasta assembly using nanopore reads would you be interested in using it to benchmark?
best regards
Sagaya

**Comment by kishwarshafin** [comment]
@reachsagaya , the choice of the model only depends on what version of guppy basecaller you have used for your data. If you have used Guppy 2.3.5 then you should use `np.json.235` where 235 reflects the guppy version number. 

If you can provide us a good reference genome and your assembly then I can do a quick test of sequence quality for you. The reference genome is expected to be the same species. Like the same way we use GRCh38 for the human genome.
