### ISSUE TITLE
MarginPolish

### ISSUE THREAD

**Issue by reiverjohn** [kishwarshafin/helen#16]
Request for MarginPolish to either:

1.    Be able to run Docker without sudo.
2.    Run docker with sudo but inside sigularity.
3.    Fix the binary so it does not segfault

Any of those 3 options would be great. I'm not sure what you need in terms of system configuration, but I'll provide you with some basics on my primary test system, and you can let me know if you need more:

    O/S CentOS v. 7.6
    Dual Intel(R) Xeon(R) CPU E5-2640 v2 CPUs
    256GB RAM
    GCC v. 4.8.5 default compiler, but other compilers are available
    Using Environment modules system
    Cmake 3.11
    O/S repos include CentOS 7 Basic, Plus, and EPEL

We have a mixture of systems, but the configuration above is pretty typical. On the university HPC, they use SLURM for resource management. On our primary lab servers we can run in standard user mode, or using Torque/PBS. All of my tests have been performed running outside of a resource management system.

Let me know what else you might need.

Thanks,
John

**Comment by kishwarshafin** [comment]
Hi John,

Sorry for the delay, I was traveling, but now I'm back in Santa Cruz and will work on this issue as soon as I am all set up. Thanks for your patience. Hopefully, this will be resolved by next week.

**Comment by kishwarshafin** [comment]
Hi John,

Can you please try this [walkthrough](https://github.com/kishwarshafin/helen/blob/master/docs/non_sudo_walkthrough.md) with all non-sudo commands. It's a small E Coli sample and should take <10 mins to run end to end.

**Comment by reiverjohn** [comment]
Hi Kishwar,

I’m out of town all this week but will run through this next week and get back to you.

Thanks
John

Sent from my iPhone

On Sep 8, 2019, at 10:38 AM, Kishwar Shafin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

Could you please try this walkthrough<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kishwarshafin_helen_blob_master_docs_non-5Fsudo-5Fwalkthrough.md&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=qSSp7ubrmnsFIIKA0J_cqA&m=wnbPhJKgPYqERebdYgMPYeusZH2_SVKYQ_yNMVTA_M4&s=N7PULIPVSmN3PnzDJDH2hBOuEUU_091LdruCEAB0zZ0&e=> with all non-sudo commands. It's a small E Coli sample and should take <10 mins to run end to end.

**Comment by kishwarshafin** [comment]
Hi John,

Due to inactivity, I am closing this issue for now. Please reopen when you see feasible and if you need any more help regarding this.
