### ISSUE TITLE
Compatibility with draft assembly from other assemblers

### ISSUE THREAD

**Issue by SHuang-Broad** [kishwarshafin/helen#19]
Hi,

I'm wondering if M + H is compatible with draft assemblies from other assemblers.
It would be great if there's already some documents showing comparisons.

Thanks!
Steve

**Comment by kishwarshafin** [comment]
Hi @SHuang-Broad ,

Yes, MP-HELEN is compatible with other assemblers as we have shown in [our paper, Figure 4c](https://www.biorxiv.org/content/10.1101/715722v1.full.pdf). 

We expect to see the same level of improvement with any assembler you use. Also, we are going to do v1.0 release in 2-3 days. If you are planning on using it, I would recommend waiting until the end of this week.

For your reference, here's the comparison:
<img width="717" alt="Screen Shot 2020-03-02 at 6 02 13 PM" src="https://user-images.githubusercontent.com/10559039/75726373-3c117d00-5cb0-11ea-920a-8867a55b10b9.png">

**Comment by SHuang-Broad** [comment]
Nice!

I do have multiple haploid assemblies and would like to see how to improve QV with polishers.
I'll keep an eye on the new release.

Thank you for the detailed explanation!

**Comment by kishwarshafin** [comment]
@SHuang-Broad ,

I have pushed the latest version to master. Please use the local installation method for now. We are doing some internal comparison with other pipelines, once that is done, we'll do the official release with results. 

I would also point you out to PEPPER (https://github.com/kishwarshafin/pepper). We are getting very competitive results with PEPPER and MP-HELEN. Please let me know if you have any issues. If you have the bandwidth, please try both tools and let us know how the assembly looks post polishing.
