### ISSUE TITLE
Models for Guppy 3.6

### ISSUE THREAD

**Issue by dominik-handler** [kishwarshafin/helen#22]
Hi,

I really like your polishing pipeline and it gives great results so far. 
Last week a new and improved version of Guppy with boosted accuracy was released. Are you planning to provide models for this version of Guppy and if so, when can we expect these?

Thank you,
Dominik

**Comment by kishwarshafin** [comment]
Hi @dominik-handler ,

Thank you for using this polisher. We are internally trying to utilize the full capacity of the Guppy basecalling improvements and that would mean significant changes in the internal algorithms. It can be made faster and better given the read qualities are higher than what this method was developed for. So, we are changing our algorithms over the next few weeks and will update everything around London Calling 2020. We can make a small iteration of guppy 3.6 in the meantime but that may not give you the same level of improvement that you'd expect. 

I will keep this issue open and will update you when this is done.

**Comment by DengHAU** [comment]
Hi，

I want to use HELEN to polish a plant genome, are the existing models suitable for a plant genome polish?

Thanks

**Comment by kishwarshafin** [comment]
Hi @dominik-handler , 

We are supporting PEPPER (https://github.com/kishwarshafin/pepper) for guppy 3.6.0 polishing as it is significantly faster and provides similar/better results than MP-HELEN. There's a 3.6.0 model added to the models directory. Please let me know if you have any issues with that.
