### ISSUE TITLE
Are existing models suitable to polish a high heterozygosity plant genome assemblies?

### ISSUE THREAD

**Issue by xiekunwhy** [kishwarshafin/helen#26]
Hi,

Which model is the best one for polishing a high heterozygosity plant genome assemblies (genome size is ~3.6Gb, het rate is >> 2%)? Assemblies(~8Gb) are generated from flye.

Best,
Kun

**Comment by kishwarshafin** [comment]
@xiekunwhy , right now HELEN has no concept of zygosity of the genome. So if it observes multiple bases at genome positions that are equally likely to be the underlying true base, it'll pick one randomly. 

The best model would be the one that matches closely to the basecaller you used for the dataset.

**Comment by xiekunwhy** [comment]
Hi,

Thank you for your reply, and I will try to use helen to polish this plant genome.
best,

Kun

**Comment by kishwarshafin** [comment]
Thanks Kun. Closing the issue, please reopen if you have any questions.
