### ISSUE TITLE
How to install helen in a gcc4.8 enrivments?

### ISSUE THREAD

**Issue by biozhangzhou** [kishwarshafin/helen#28]
The Servers I'm using is RedHat4.8 && gcc4.8;
I have spent more than one day in installing helen, the error were coming one after another, anybody met the similar pros? 
Please notice me. Thks.

**Comment by kishwarshafin** [comment]
Hi @biozhangzhou , sorry to hear that.

Can you use a docker? I don't have any experience with redhat.

**Comment by biozhangzhou** [comment]
thank you,I will try to ask my administrator to install docker.

**Comment by kishwarshafin** [comment]
please reopen the issue if you can't find a way to make it work. Thanks.
