### ISSUE TITLE
How to train a new model with in lab testing data

### ISSUE THREAD

**Issue by yipukangda** [kishwarshafin/helen#31]
Our lab is doing research on some channel protein, the sequencing error seems different from R9 pore, so we want to training marginpolish/Helen with these new data, could you tell me how to do it, thanks.

**Comment by kishwarshafin** [comment]
Hi @yipukangda ,

This sounds very interesting, and thanks for choosing MP/HELEN for your experiment. If this is a new channel and the error mode is different, I'd suggest you try PEPPER (https://github.com/kishwarshafin/pepper) to train and test your new pore. The reason would be simplicity and a faster trial-error loop. If you open an issue there or send me an email at shafin@ucsc.edu, I can help you with setting up a training run. 

Things you need to train a polisher:
1) A truth assembly (high-quality assembly that can be regarded as the truth)
2) A draft assembly (an assembly that you are trying to improve)
3) Reads aligned to the draft assembly.

If you have these, open an issue in PEPPER repository and I will help you with that.

**Comment by yipukangda** [comment]
@kishwarshafin Thanks a lot, I will read the manual and open an issue soon.
