### ISSUE TITLE
Only Polish interested sequences 

### ISSUE THREAD

**Issue by Yechao94** [kishwarshafin/helen#34]
Hi，I used shasta to assemble the sequencing data from nanopore. I have hundreds of assembled results, and I only focus on those sequences that do not appear in the reference genome (NRS). So, I want to know if I could use M-H to only polish the NRS I extracted from the assembly results instead of the entire assembly fasta file?

**Comment by kishwarshafin** [comment]
Hi @Yechao94 ,

I'd suggest using PEPPER (https://github.com/kishwarshafin/pepper/releases/tag/v0.1) and use `-r` parameter where you can specify regions/contigs you want to polish.

**Comment by Yechao94** [comment]
Great, I will have a try!
Thanks a lot.

**Comment by kishwarshafin** [comment]
great, I'll close this issue.
