### ISSUE TITLE
there are no other mammal models other than human?

### ISSUE THREAD

**Issue by xdkong** [kishwarshafin/helen#36]
I have downloaded the available models, but there were no models other than human. My data was mammal but isn't human，how can I get the right model.Thank you for your help.

**Comment by xdkong** [comment]
Who can help me? Thank you very much.

**Comment by kishwarshafin** [comment]
@xdkong , really sorry for not getting back to you regarding this. As mentioned in the readme, we now suggest users use PEPPER for polishing genome assemblies. Can you please open the issue in that repository so I can help you better and not lose track?
https://github.com/kishwarshafin/pepper
