### ISSUE TITLE
stitch.py ValueError triggered by contig sequence name

### ISSUE THREAD

**Issue by krobison13** [kishwarshafin/helen#6]
stitch.py throws a ValueError if one of my contigs is named the following, but works fine if I rename it to something like CLUS3951

` bc.1+2.clus.3951.fa.poa:1.0-7835.0`

It is apparently trying to convert the 7835.0 at the end into an integer

`  File "stitch.py", line 93, in <module>
    process_marginpolish_h5py(FLAGS.sequence_hdf, FLAGS.output_dir, FLAGS.threads)
  File "stitch.py", line 58, in process_marginpolish_h5py
    consensus_sequence = stich_object.create_consensus_sequence(hdf_file_path, contig, chunk_keys, threads)
  File "modules/python/Stitch.py", line 280, in create_consensus_sequence
    sequence_chunk_key_list.append((contig, int(st), int(end)))
ValueError: invalid literal for int() with base 10: '7835.0'
`

**Comment by kishwarshafin** [comment]
I was able to re-generate the error internally; I will add a test for this case and update you on this. 

Just to let you know, all the tests we do are offline and takes a lot of time to perform all the tests before we merge to master. So, it may take a little bit of time before you see the change. 

Thank you for posting, it's really helpful.

**Comment by kishwarshafin** [comment]
Hello, I have fixed this issue, please reopen this issue or let us know if you find this happening again. Thank you again for reporting.
