### ISSUE TITLE
How does marginpolish + helen compare to nanopolish?

### ISSUE THREAD

**Issue by phiweger** [kishwarshafin/helen#8]
Hi,

I only found comparisons for racon and medaka, however, the best results I see are from nanopolish, so I wonder how m + h compares to it.

Thanks,
Adrian

**Comment by kishwarshafin** [comment]
Hi Adrian,

As we don't embed any signal level information, we haven't compared against nanopolish. We are focusing on doing a deep analysis of MP + HELEN against Racon + Medaka first. Then depending on resource availability and necessity, we will compare with nanopolish.

**Comment by kishwarshafin** [comment]
Hi Adrian,

I'll close this issue for now. Will open it again when we do compare with nanopolish. Please feel free to open this issue if you have any other question.
